[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.109.0"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/rss.xml"
  to = "/index.xml"

